module try_catch;

fn main() -> i32 {
    try {
        throw wec::Exception("1 is not equal to 2");
    } catch (e: wec::Exception) {
        wec.print("Error: " + e.message);
    }

    try {
        wec.print("Working!");
    } catch (e: wec::Exception) {
        wec.print("Error: " + e.message);
    }
    return 0;
}